# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      issues: write  # Add this if not present
      pull-requests: write  # Add this if not present

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'corretto'

    - name: Build with Maven
      run: mvn -B package -DskipTests -Drevision=${{ github.event.release.tag_name }} --file pom.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: amazon-s3-encryption-cli-client-${{ github.event.release.tag_name }}.jar
        path: target/amazon-s3-encryption-cli-client-${{ github.event.release.tag_name }}.jar

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./target/amazon-s3-encryption-cli-client-${{ github.event.release.tag_name }}.jar
        asset_name: amazon-s3-encryption-cli-client-${{ github.event.release.tag_name }}.jar
        asset_content_type: application/java-archive
